# Generated by Django 3.2.7 on 2021-11-03 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 11, 3, 10, 6, 4, 573089, tzinfo=utc)),
        ),
    ]
